[project]
name = "vector-test"
version = "0.1.0"
description = "Python/ML projects"
readme = "README.md"
requires-python = ">=3.10"

# uv add 로 설치한 패키지들이 여기에 명시됩니다.
dependencies = [
    "matplotlib>=3.8.0",
    "numpy>=1.26.0",
    "pandas>=2.2.0",
    "scikit-learn>=1.4.0",
    "ucimlrepo>=0.0.6",
]

# 1. C 드라이브 외부에 가상환경 생성 및 의존성 동기화
uv sync --active --python 3.11 --project . --venv C:\dev\venv_ml2

# 2. 지정한 가상환경으로 실행
uv run --venv C:\dev\venv_ml2 3_1_bias_variance_tradeoff.py

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"